config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_for :chefs
  resources :cuisines do
    resources :recipes
    resources :reservations
    resources :reviews
  end

  resources :authentication

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :cuisine
  belongs_to :chef
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_cuisine
  before_action :find_recipe, only: [:destroy, :edit, :update]

  def create
    @recipe = @cuisine.recipes.new(recipe_params)
    @recipe.chef = current_chef
    @recipe.save

    if @recipe.save
      redirect_to cuisine_path(@cuisine)
    else
      #render 'new'
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to cuisine_path(@cuisine)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to cuisine_path(@cuisine)
  end

  private
  def find_cuisine
    @cuisine = Cuisine.find(params[:cuisine_id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :price, :image)
  end

  def find_recipe
    @recipe = @cuisine.recipes.find(params[:id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if current_chef == @cuisine.chef %>
  <%= form_for([@cuisine, @cuisine.recipes.build]) do |f| %>

   <div class="field">
      <%= f.file_field :image %>
    </div>
    <br>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <%= f.number_field :price, class: :text_field, step: :any %>
    </div>
    <br>

    <div class="actions">
      <%= f.submit 'Add Recipe', class: 'btn btn-warning' %>
    </div>
  <% end %>
<% end %>

app/views/recipes/_recipe.html.erb
<% @recipes.each do |recipe| %>
<br>
  <h5><div> <%= recipe.title %> </div></h5>
  <h6><b>Price:</b> <%= recipe.price %> </h6>
  <%= image_tag recipe.image_url(:thumb).to_s %>
  <br>
  <% if current_chef == @cuisine.chef %>
     <%= link_to "Edit Recipe", edit_cuisine_recipe_path(recipe.cuisine, recipe) %> |
    <%= link_to "Delete Recipe", [recipe.cuisine, recipe], method: :delete  %>
    <br>
    <br>
  <% end %>
<% end %>

<%= render 'recipes/form' %>

app/views/recipes/edit.html.erb
<br>
<%= link_to '&#x276e;'.html_safe, :back, class: 'btn btn-secondary btn-circle' %> <br>

<% if current_chef == @cuisine.chef %>
  <%= form_for([@cuisine, @recipe]) do |f| %>
  <br>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <%= f.number_field :price, class: :text_field, step: :any %>
    </div>
    <br>

    <div class="actions">
      <%= f.submit 'Add Recipe', class: 'btn btn-warning' %>
    </div>
  <% end %>
<% end %>