config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_for :chefs
  resources :cuisines do
    resources :recipes
    resources :reservations
    resources :reviews
  end

  resources :authentication

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  belongs_to :chef
  has_many :recipes, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :set_cuisine, only: [:show, :edit, :update, :destroy]

  def index
    #@cuisines = Cuisine.where(["title LIKE ?","%#{params[:search]}%"])
    @cuisines = Cuisine.where('lower(city) LIKE lower(?) OR lower(city) LIKE lower(?)', "%#{params[:search]}%", "%#{params[:search]}%")
  end
  # GET /cuisines
  # GET /cuisines.json

  # GET /cuisines/1
  # GET /cuisines/1.json
  def show
    @recipes = Recipe.where(cuisine_id: @cuisine).order('created_at DESC')
    @reservations = Reservation.where(cuisine_id: @cuisine).order('created_at DESC')
    @reviews = Review.where(cuisine_id: @cuisine).order('created_at DESC')
    @recipe_orders = @cuisine.recipes.pluck(:title, :price).map { |names| names.join(" ") }
  end

  # GET /cuisines/new
  def new
    @cuisine = Cuisine.new
  end

  # GET /cuisines/1/edit
  def edit
  end

  # POST /cuisines
  # POST /cuisines.json
  def create
    @cuisine = Cuisine.new(cuisine_params)
    @cuisine.chef = current_chef
    respond_to do |format|
      if @cuisine.save
        format.html { redirect_to @cuisine, notice: 'Cuisine was successfully created.' }
        format.json { render :show, status: :created, location: @cuisine }
      else
        format.html { render :new }
        format.json { render json: @cuisine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuisines/1
  # PATCH/PUT /cuisines/1.json
  def update
    respond_to do |format|
      if @cuisine.update(cuisine_params)
        format.html { redirect_to @cuisine, notice: 'Cuisine was successfully updated.' }
        format.json { render :show, status: :ok, location: @cuisine }
      else
        format.html { render :edit }
        format.json { render json: @cuisine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuisines/1
  # DELETE /cuisines/1.json
  def destroy
    @cuisine.destroy
    respond_to do |format|
      format.html { redirect_to cuisines_url, notice: 'Cuisine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cuisine_params
    params.require(:cuisine).permit(:title, :about, :availability, :location, :city, :address)
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/views/cuisines/_form.html.erb
  <div class="col-md-8 col-md-offset-2 text-center">
    <% if chef_signed_in? %>
      <%= form_for(cuisine) do |f| %>
        <% if cuisine.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(cuisine.errors.count, "error") %> prohibited this cuisine from being saved:</h2>

            <ul>
            <% cuisine.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <!-- <%= f.label :title %> -->
          <%= f.text_field :title, placeholder: 'Cuisine title', class: 'form-control' %>
        </div>

        <br>

        <div class="field">
          <!-- <%= f.label :about %> -->
          <%= f.text_area :about, placeholder: 'Tell us about you and your cuisine', class: 'form-control', size: '30x8' %>
        </div>

        <br>

        <div class="field">
          <!-- <%= f.label :availability %> -->
          <%= f.text_field :availability, placeholder: :availability, class: 'form-control' %>
        </div>

        <br>

        <div class="field">
          <!-- <%= f.label :location %> -->
          <%= f.country_select :location, include_blank: 'Select a country' %>
          <br>
          <br>
          <%= f.text_field :city, placeholder: :city, class: 'form-control' %>
        </div>
        <br>

         <div class="field">
          <!-- <%= f.label :address %> -->
          <%= f.text_field :address, placeholder: :address, class: 'form-control' %>
        </div>
        <br>
        <div class="actions">
          <%= f.submit class: 'btn btn-warning' %>
        </div>
        <br>
      <% end %>
    <% end %>
  </div>

app/views/cuisines/edit.html.erb
<br>
<%= link_to '&#x276e;'.html_safe, :back, class: 'btn btn-secondary btn-circle' %> <br><br>

<% if current_chef.id == @cuisine.chef_id %>
  <h1>Editing Cuisine</h1>

  <%= render 'form', cuisine: @cuisine %>
<% end %>

app/views/cuisines/index.html.erb
<% if user_signed_in? or chef_signed_in? %>
  <div class="cuisine_background">
    <div class="cuisine_background-content">
      <h1>Cuisines</h1>
      <div class="box">
        <% @cuisines.each do |cuisine| %>
          <%= link_to cuisine do %>
            <div class="btn btn-secondary">  
              <%= cuisine.title %><br>
              <%= cuisine.about %><br>
              <%= cuisine.availability %><br>
              <%= cuisine.location %><br>
              <%= cuisine.city %><br> 
              <%= cuisine.address %><br> 
            </div> 
          <% end %>
        <% end %>
      </div>
      <br>
      <% if chef_signed_in? %>
        <%= link_to 'New Cuisine', new_cuisine_path, class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/cuisines/new.html.erb
<br>
<%= link_to '&#x276e;'.html_safe, cuisines_path, class: 'btn btn-secondary btn-circle' %>
<br>
<br>
<% if chef_signed_in? %>
	<h1>New Cuisine</h1>

  		<%= render 'form', cuisine: @cuisine, class: 'btn btn-primary'%>
      <br>
<% end %>

app/views/cuisines/show.html.erb
<div class="cuisine_chefs">
   <br> <%= link_to '&#x276e;'.html_safe, cuisines_path, class: 'btn btn-secondary btn-circle' %> <br><br>
  <div class="navbar-nav mr-0 ml-lg-auto">
    <h1> <%= @cuisine.title %> </h1>
    About: <%= @cuisine.about %><br>
    Availability: <%= @cuisine.availability %><br>
    Location: <%= @cuisine.location %>,
    <%= @cuisine.city %>,
    <%= @cuisine.address %><br>
    <li><% if current_chef == @cuisine.chef %>
      <%= link_to 'Edit', edit_cuisine_path(@cuisine) %> |
      <%= link_to 'Delete', @cuisine, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %></li>
  </div>
</div>


<br>
<br>

<h1>Menu</h1>
<%= render 'recipes/recipe' %>
<br>
<br>

<% if user_signed_in? or current_chef == @cuisine.chef %>
  <h2>Reservations:</h2>
  <%= render 'reservations/reservation' %>
<% end %>

<br>

  <h2>Reviews:</h2>
  <%= render 'reviews/review' %>

<br>