config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_for :chefs
  resources :cuisines do
    resources :recipes
    resources :reservations
    resources :reviews
  end

  resources :authentication

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many :cuisines, dependent: :destroy
  has_many :recipes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :phone, presence: true

  def login=(login)
    @login = login
  end

  def login
    @login || self.phone || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(phone) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:phone) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  belongs_to :chef
  has_many :recipes, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :cuisine
  belongs_to :chef
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :cuisine
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cuisine
  belongs_to :user
  #validates_presence_of :grade
  #validates_presence_of :comment
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :phone, presence: true

  def login=(login)
    @login = login
  end

  def login
    @login || self.phone || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(phone) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:phone) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [:phone, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :set_cuisine, only: [:show, :edit, :update, :destroy]

  def index
    #@cuisines = Cuisine.where(["title LIKE ?","%#{params[:search]}%"])
    @cuisines = Cuisine.where('lower(city) LIKE lower(?) OR lower(city) LIKE lower(?)', "%#{params[:search]}%", "%#{params[:search]}%")
  end
  # GET /cuisines
  # GET /cuisines.json

  # GET /cuisines/1
  # GET /cuisines/1.json
  def show
    @recipes = Recipe.where(cuisine_id: @cuisine).order('created_at DESC')
    @reservations = Reservation.where(cuisine_id: @cuisine).order('created_at DESC')
    @reviews = Review.where(cuisine_id: @cuisine).order('created_at DESC')
    @recipe_orders = @cuisine.recipes.pluck(:title, :price).map { |names| names.join(" ") }
  end

  # GET /cuisines/new
  def new
    @cuisine = Cuisine.new
  end

  # GET /cuisines/1/edit
  def edit
  end

  # POST /cuisines
  # POST /cuisines.json
  def create
    @cuisine = Cuisine.new(cuisine_params)
    @cuisine.chef = current_chef
    respond_to do |format|
      if @cuisine.save
        format.html { redirect_to @cuisine, notice: 'Cuisine was successfully created.' }
        format.json { render :show, status: :created, location: @cuisine }
      else
        format.html { render :new }
        format.json { render json: @cuisine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuisines/1
  # PATCH/PUT /cuisines/1.json
  def update
    respond_to do |format|
      if @cuisine.update(cuisine_params)
        format.html { redirect_to @cuisine, notice: 'Cuisine was successfully updated.' }
        format.json { render :show, status: :ok, location: @cuisine }
      else
        format.html { render :edit }
        format.json { render json: @cuisine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuisines/1
  # DELETE /cuisines/1.json
  def destroy
    @cuisine.destroy
    respond_to do |format|
      format.html { redirect_to cuisines_url, notice: 'Cuisine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cuisine_params
    params.require(:cuisine).permit(:title, :about, :availability, :location, :city, :address)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_cuisine
  before_action :find_recipe, only: [:destroy, :edit, :update]

  def create
    @recipe = @cuisine.recipes.new(recipe_params)
    @recipe.chef = current_chef
    @recipe.save

    if @recipe.save
      redirect_to cuisine_path(@cuisine)
    else
      #render 'new'
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to cuisine_path(@cuisine)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to cuisine_path(@cuisine)
  end

  private
  def find_cuisine
    @cuisine = Cuisine.find(params[:cuisine_id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :price, :image)
  end

  def find_recipe
    @recipe = @cuisine.recipes.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_cuisine

  def create
    @review = @cuisine.reviews.new(review_params)
    @review.user = current_user
    @review.save

    if @review.save
      redirect_to cuisine_path(@cuisine)
    else
      #render 'new'
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  private
  def find_cuisine
    @cuisine = Cuisine.find(params[:cuisine_id])
  end

  def review_params
    params.require(:review).permit(:grades, :comments)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_nav.html.erb
<% if chef_signed_in? %>
    <%= render '/layouts/nav_chef' %>
<% elsif user_signed_in? %>
    <%= render '/layouts/nav_user' %>
<% else %>
    <%= render '/layouts/nav_guest' %>
<% end %>

app/views/layouts/_nav_chef.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="/"><%= image_tag 'logo.png', width: '100' %></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav">
     <li class="nav-item"><%= link_to 'Cuisine', cuisines_path, class: 'nav-link' %></li>
    </ul>

<ul class="nav navbar-nav navbar-logo mx-auto">
     <li class="nav-item"> <%= form_tag cuisines_path, :method => 'get' do %>
      <%= text_field_tag :search, nil, placeholder: "Search cuisines here", class: 'search-round-bar'%>
      <%= submit_tag "&#x1f374;".html_safe, class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>
    </li>
</ul>

    <ul class="nav navbar-nav pull-right">
      <li class="nav-item"><%= link_to 'Settings', edit_chef_registration_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Sign Out', destroy_chef_session_path, :method => :get, class: 'nav-link' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <a class="navbar-brand" href="/"><%= image_tag 'logo.png', width: '100' %></a>
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="/"><%= image_tag 'logo.png', width: '100' %></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to 'Cuisine', cuisines_path, class: 'nav-link' %></li>
    </ul>

<ul class="nav navbar-nav navbar-logo mx-auto">
     <li class="nav-item"> <%= form_tag cuisines_path, :method => 'get' do %>
      <%= text_field_tag :search, nil, placeholder: "Search cuisines here", class: 'search-round-bar'%>
      <%= submit_tag "&#x1f374;".html_safe, class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>
    </li>
</ul>

    <ul class="nav navbar-nav pull-right">
      <li class="nav-item"><%= link_to 'Settings', edit_user_registration_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Sign Out', destroy_user_session_path, :method => :get, class: 'nav-link' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EatYV</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag 'favicon.ico' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <center>
      <%= yield %>
    </center>
  </body>
</html>